#!/bin/bash

# This wrapper will intercept the invocation of keepalived, then parse the
# commandline to extract the router id.  Once it has the router id it will
# start a keepalived in a new docker container in the proper namespace.

IMAGE_NAME=${KEEPALIVED_IMAGE_NAME:-blobmirror:5000/cirrus/openstack-dev}
IMAGE_TAG=${KEEPALIVED_IMAGE_TAG:-20160731.0-11002e.25.70d62e6}

# Extract router uuid from args by extracting the first uuid in the arguments
ARGS="$@"
ROUTER_ID=$(echo $ARGS|perl -pe 's/.*(\w{8}-\w{4}-\w{4}-\w{4}-\w{12}).*/$1/')
NAME=keepalived-${ROUTER_ID}

# Stop and remove existing keepalived container if it exists
docker stop $NAME || true
docker rm -f $NAME || true

# Start new container with proper permissions
exec /usr/bin/docker run --detach \
    -v /var/run/netns:/var/run/netns:shared \
    -v /var/lib/neutron:/var/lib/neutron \
    --net host \
    --pid host \
    --privileged \
    --name $NAME \
    ${IMAGE_NAME}:${IMAGE_TAG} \
    ip netns exec qrouter-${ROUTER_ID} /usr/sbin/keepalived -n -l -D $ARGS
